import { Inter } from "next/font/google";
import "../globals.css";
import Header from "../components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "App",
  description: "Generated by create next app",
};

export default function headLayout({ children }) {
  return (
    <>
        
        <Header></Header>
        {children}
    </>
       
  );
}
